


all:
	inkscape analyse/classes.svg --export-pdf=analyse/classes.pdf
	inkscape conception/classes.svg --export-pdf=conception/classes.pdf
	inkscape conception/CreationEpisodesPersoParties.svg --export-pdf=conception/CreationEpisodesPersoParties.pdf
	inkscape conception/ctrl.svg --export-pdf=conception/ctrl.pdf
	inkscape conception/dao.svg --export-pdf=conception/dao.pdf
	pdflatex rapport

clean:
	rm -f *.{log,aux,toc,out}


